services:
  sevenmark_server:
    build: .
    container_name: sevenmark_server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - docker.env
    ports:
      - "9000:9000"