name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack and wasm-opt
        run: |
          which wasm-pack || cargo install wasm-pack
          which wasm-opt || cargo install wasm-opt

      - name: Release Build (Workspace)
        run: cargo build --release --workspace

      - name: Run Tests (Parser with locations)
        run: cargo test -p sevenmark_parser --features include_locations -- --nocapture

      - name: Run Tests (Wasm)
        run: cargo test -p sevenmark_wasm -- --nocapture

      - name: Run Tests (Server)
        run: cargo test -p sevenmark_server -- --nocapture

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Test WASM build (Web)
        working-directory: ./crates/sevenmark_wasm
        run: wasm-pack build --target web

      - name: Test WASM build (Bundler)
        working-directory: ./crates/sevenmark_wasm
        run: wasm-pack build --target bundler

      - name: Test WASM build (Node.js)
        working-directory: ./crates/sevenmark_wasm
        run: wasm-pack build --target nodejs
